### ISSUE TITLE
ColorPicker Resets Color to Fallback Color When Moving Between Views (E.G. PSLinkListCell)

### ISSUE THREAD

**Issue by willsmillie** [atomikpanda/libcolorpicker#1]
Pretty much what the title says.. Read through the docs and searched online and haven't been able to find a solution.

**Comment by rob311fan** [comment]
What iOS version?

**Comment by willsmillie** [comment]
iOS 10

**Comment by rob311fan** [comment]
I'll look into it tonight. Would you mind uploading a test tweak with just the relevant code?

**Comment by willsmillie** [comment]
Sure. Do you want source code, or just a compiled tweak?

**Comment by rob311fan** [comment]
Both please

**Comment by rob311fan** [comment]
Source

**Comment by willsmillie** [comment]
Created a repo here: https://github.com/williamfs/lcptest

**Comment by rob311fan** [comment]
Excellent. I will follow up with you

**Comment by rob311fan** [comment]
[lcpsettings.zip](https://github.com/atomikpanda/libcolorpicker/files/1233024/lcpsettings.zip)
replace these files in your settings folder

**Comment by willsmillie** [comment]
Awesome! Thanks!

**Comment by rob311fan** [comment]
You're welcome. Let me know what f you need anymore help.
