### ISSUE TITLE
Settings crashes whenever I try to select a color

### ISSUE THREAD

**Issue by ghost** [atomikpanda/libcolorpicker#15]
iPhone X iOS 13.4 - settings crashes whenever gui for selecting a color is opened see below crash report.

[LibColorPicker crash report.txt](https://github.com/atomikpanda/libcolorpicker/files/4468736/LibColorPicker.crash.report.txt)

**Comment by iM4CH3T3** [comment]
Yep , same here on iOS 13.4.1 iPhone 7
Checkra1n 

https://www.dropbox.com/s/7ha5qsrdjais99a/Preferences-2020-04-14-054341.symbolicated.ips?dl=0

**Comment by ghost** [comment]
You have to get alderis color picker from Chairz repo to fix it.

**Comment by Nosskirneh** [comment]
libcolorpicker was updated a few weeks ago to fix this. Alderis does not support transparency as of now, but it's otherwise a library that could easily be installed and used by the same tweaks that use libcolorpicker.
