### ISSUE TITLE
Hi, libcolorpicker crashes on ios 13.4.1, iPhoneX.

### ISSUE THREAD

**Issue by MinazukiDev** [atomikpanda/libcolorpicker#16]
libcolorpicker crashes on ios 13.4.1, iPhoneX.

**Comment by alven-shin** [comment]
Same it crashes my preferences on iOS iPhone 8 Plus 13.5 using the unc0ver. Here’s a crash report: https://pastebin.com/qZXWx9rV

**Comment by Nosskirneh** [comment]
Fixed in https://github.com/atomikpanda/libcolorpicker/commit/154b38896fdb40bc5fe315067023244eb15fc2e6. Version 1.6.8 has been submitted.
