### ISSUE TITLE
Sliders doesn't update when start color has zero saturation

### ISSUE THREAD

**Issue by Nosskirneh** [atomikpanda/libcolorpicker#2]
[This](https://www.dropbox.com/s/0kxn2k1z3v2td7e/ScreenRecording_08-19-2018%2016-03-22.mp4?dl=0) happens only when loading a color with zero saturation.

Probably something [here](https://github.com/atomikpanda/libcolorpicker/blob/master/PFColorAlert.mm#L285) that needs to change.

**Comment by atomikpanda** [comment]
Is this still an issue with the latest version? @Nosskirneh

**Comment by Nosskirneh** [comment]
[Yes](https://www.dropbox.com/s/24732eq9krxf6ba/zero_saturation.mp4?dl=0). I'll try to look into a solution.

**Comment by Nosskirneh** [comment]
Fixed in 1.6.3-1.
