### ISSUE TITLE
Can you add a button called Paste From Pasteboard

### ISSUE THREAD

**Issue by atebitsy-old** [atomikpanda/libcolorpicker#6]
Can you add a button called Paste From Pasteboard

So if you’ve copied a hex code online you can go to the color picker and just click paste from paste board instead of have to click then paste if that makes sense?

**Comment by Nosskirneh** [comment]
I like the idea. Might look into it!

**Comment by atebitsy-old** [comment]
aww woo hoo thanks so much and i’m glad my idea was good :) and is there any chance we can remove the 2” border around the Colour cells for a cleaner look maybe please if that makes sense?

**Comment by Nosskirneh** [comment]
Implemented in a previous version.
