### ISSUE TITLE
Hex button crashes settings app

### ISSUE THREAD

**Issue by sevenpastzeero** [atomikpanda/libcolorpicker#7]
Hello,
I have an issue with version 1.6.3. Every time I press the Hex button it crashes the settings app.
I have tested this with two tweaks and it was the same.
iPhone 7+, 12.1.1, unc0ver 3.2.1.
Here's a screen recording: https://drive.google.com/file/d/1dT5OtzF5lJLu0FYvmUGuRqOuv2fLuo8d/view?usp=drivesdk
The issue is not presented when I downgrade to old 1.6.1 version.

**Comment by atomikpanda** [comment]
Thanks for the report we are working on fixing this issue currently.

**Comment by Nosskirneh** [comment]
Fixed in 1.6.3-1.

**Comment by nik312123** [comment]
This issue has started occurring for me. I am on iOS 13.4.1 on an iPhone 6S.
