### ISSUE TITLE
Color Picker instantly closes

### ISSUE THREAD

**Issue by blackma9ick** [atomikpanda/libcolorpicker#8]
When I try to use the color picker in the Settings app ( trying to configure Flame ), it instantly closes and won’t let me interact with it.
If I hold my finger on it, it stays there, but the background semi-transparent black goes away, and when I release, it also entirely goes away.
I tried to re-install but I can’t seem to get it working.
I am running the latest version of libcolorpicker.

**Comment by Nosskirneh** [comment]
Thanks for the report! We’re onto it, stay tuned for an update!

**Comment by NoisyFlake** [comment]
Any update on this?

**Comment by Nosskirneh** [comment]
We have discussed this internally and decided to remove ARC from the main class and instead rely on autoreleasing it. We hope to release a new build soon.

**Comment by Nosskirneh** [comment]
Fixed in 1.6.3-1.
